name: Hello World Workflow

on:
  push:
    branches:
      - main  # Triggers the action when there's a push to the main branch
  pull_request:  # Also runs on pull requests
    branches:
      - main

jobs:
  say-hello:
    runs-on: ubuntu-latest  # The environment where the action runs

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3  # Check out the code in the repository

      - name: Make script executable
        run: chmod +x ./scripts/script.sh

      - name: Say Hello World
        run: ./scripts/script.sh qa $pwd
