name: Upload to Azure Blob Storage

on:
  push:
    branches:
      - main

jobs:
  upload_to_blob:
    runs-on: ubuntu-latest
    environment: dev
    
    steps:
    # Checkout the repository to get access to the files to be uploaded
    - name: Checkout repository
      uses: actions/checkout@v3

    # Log in to Azure CLI
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Upload files to Azure Blob Storage
    - name: Upload files to Azure Blob Storage
      run: |
        # Install the Azure CLI Storage module
        az extension add --name storage-preview

        # Upload the file to the blob container
        az storage blob upload-batch \
          --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
          --destination ${{ secrets.AZURE_STORAGE_CONTAINER }} \
          --source ./htmltemplates \
          --auth-mode key
